In [87]:
#We are going to import from Pandas,Numpy, and sklearn and store the data frame into the variable df [18BIS0103]
import pandas as pd
import numpy as np
from datetime import datetime

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

df = pd.read_csv("IOT-temp dataset task 2_UPDATED.csv")
print (df.head())


   Date  Month  Year  Hours  Min  out/in  temp
0     8     12  2018      9   30       2  29.0
1     8     12  2018      9   30       2  29.0
2     8     12  2018      9   29       1  41.0
3     8     12  2018      9   29       1  41.0
4     8     12  2018      9   29       2  31.0


In [88]:
#REMOVING DUPLICATE
df_dropped = df

#We are going to Remove duplicate values
df_dropped.drop_duplicates(inplace=True)
df_dropped[df_dropped.duplicated()]
entries=df_dropped.shape
entries = int(entries[0])
print(entries)
#We also stored the number of entries for later use
#These are the number of rows after the duplicated values are removed

37281


In [89]:
#We are going to remove the missing data and put in the MEAN value

missing_value = ['temp']

for column in missing_value:
    df_dropped[column] = df_dropped[column].replace(np.NaN, np.NaN)
    mean = int(df_dropped[column].mean(skipna=True))
    df_dropped[column] = df_dropped[column].replace(np.NaN, mean)
    
print(df_dropped.isnull().sum())

#The below is a proof that the Data is free of null values

Date      0
Month     0
Year      0
Hours     0
Min       0
out/in    0
temp      0
dtype: int64


In [85]:
#NOTE : THIS IS THE SAME STEP AS THE PREVIOUS ONE, EXECPT WE USE MEDIAN VALUE
#We are going to remove the missing data and put in the median value

missing_value = ['temp']

for column in missing_value:
    df_dropped[column] = df_dropped[column].replace(np.NaN, np.NaN)
    median = int(df_dropped[column].median(skipna=True))
    df_dropped[column] = df_dropped[column].replace(np.NaN, median)
    
print(df_dropped.isnull().sum())

#The below is a proof that the Data is free of null values

Date      0
Month     0
Year      0
Hours     0
Min       0
out/in    0
temp      0
dtype: int64


In [90]:
#Split the dataset into out and in
 
df_dropped_out = df_dropped[df_dropped['out/in'] ==1] #This Varialble has OUT in it
df_dropped_in = df_dropped[df_dropped['out/in'] ==2] #This variable has IN in it

print(df_dropped_out.head())
print(df_dropped_in.head())

    Date  Month  Year  Hours  Min  out/in  temp
2      8     12  2018      9   29       1  41.0
10     8     12  2018      9   25       1  42.0
16     8     12  2018      9   21       1  41.0
20     8     12  2018      9   19       1  42.0
24     8     12  2018      9   17       1  41.0
    Date  Month  Year  Hours  Min  out/in  temp
0      8     12  2018      9   30       2  29.0
4      8     12  2018      9   29       2  31.0
6      8     12  2018      9   28       2  29.0
8      8     12  2018      9   26       2  29.0
12     8     12  2018      9   24       2  29.0


In [91]:
#Splitting dataset for training and testing for OUT --> 1 for out, 2 --> IN

X1 = df_dropped_out.iloc[:, 0:6]
y1 = df_dropped_out.iloc[:, 6]
X1_train, X1_test, y1_train, y1_test = train_test_split(X1,y1,random_state=0, test_size=0.2)

In [92]:
#Feature scaling for OUT
sc_X1 = StandardScaler()
X1_train = sc_X1.fit_transform(X1_train)
X1_test = sc_X1.transform(X1_test)

In [103]:
#Splitting dataset for training and testing for IN --> 1 for out, 2 for in

X2 = df_dropped_in.iloc[:, 0:6]
y2 = df_dropped_in.iloc[:, 6]
X2_train, X2_test, y2_train, y2_test = train_test_split(X2,y2,random_state=0, test_size=0.2)

In [94]:
#Feature scaling for IN
sc_X2 = StandardScaler()
X2_train = sc_X2.fit_transform(X2_train)
X2_test = sc_X2.transform(X2_test)

In [95]:
#Define the model: Init K-NN for OUT | n_neighbors=3
classifier_OUT = KNeighborsClassifier(n_neighbors=3, p='weighted', metric='euclidean')

In [96]:
#Fit Model for OUT
classifier_OUT.fit(X1_train, y1_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3, p='weighted')

In [97]:
#Define the model: Init K-NN for IN | n_neighbors=3
classifier_IN = KNeighborsClassifier(n_neighbors=3, p=2, metric='euclidean')

In [98]:
#Fit Model for IN
classifier_IN.fit(X1_train, y1_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [99]:
import math #OUT
math.sqrt(len(y1_test))

73.93916418245476

In [100]:
#IN
math.sqrt(len(y2_test))

44.609416046390926

In [101]:
#Predict the test results for OUT
y1_pred = classifier_OUT.predict(X1_test)

In [105]:
#Predict the test results for IN
y2_pred = classifier_IN.predict(X2_test)

In [102]:
#Evaluate model OUT
cm_out = confusion_matrix(y1_test, y1_pred)
print (cm_out)
print (f1_score(y1_test, y1_pred, average='weighted'))

[[  1   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   2   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  1   2   3  10   3   1   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  1   4  16  28  84   6   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  1   1  12  96  61  85   0   1   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   1  22  98  36  43   4   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   1   9  46  84  92   6   0   0   0   1   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   2   3  18 127  62  40   1   0   0   0   0   1   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   2  16  62  29  25   5   1   0   0   0   

In [106]:
#Evaluate model IN
cm_in = confusion_matrix(y2_test, y2_pred)
print (cm_in)
print (f1_score(y2_test, y2_pred, average='weighted'))

[[  0   0   0   0   0   0   0   0   0   1   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   0   0   0   0   1   0   0   0   0   4   0   0   0]
 [  0   0   0   0   0   0   0   0   0   5   0   0   0   0  13   0   0   0]
 [  0   0   0   0   0   0   0   0   0   3   0   0   2   2  32   0   1   0]
 [  0   0   0   0   0   0   0   0   0  13   0   0  11   2  76   0  11   0]
 [  0   0   0   0   0   0   0   0   0   8   0   0  19   2 116   0  11   0]
 [  0   0   0   0   0   0   0   0   0   2   0   0  13   9 267   0   9   0]
 [  0   0   0   0   0   0   0   0   0   5   0   0  45   9 219   1   3   0]
 [  0   0   0   0   0   0   0   0   0   9   0   0  41  13 264   0   4   0]
 [  0   0   0   0   0   0   0   0   0  27   0   0  24   7 228   0   4   1]
 [  0   0   0   0   0   0   0   0   0   2   0   0  38  13 171   0   7   1]
 [  0   0   0   0   0   0   0   0   0   0   0   0  19   6 121   0   6   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   6   4  50   0   0   0]
 [  0   0   0   0   0   0