In [28]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
df = pd.read_excel("Lab task 4 regression.xlsx")
df

S.No company  Age Gender Qualification  no of experience in years  \
0      1    ABBB   21      M           B.E                          0   
1      2    ABBB   24      F           M.E                          1   
2      3    ABBB   30      M           M.E                          5   
3      4    ABBB   23      M           B.E                          2   
4      5    ABBB   21      F           B.E                          0   
5      6    Oxon   27      M           B.E                          4   
6      7    Oxon   29      M           B.E                          5   
7      8    Oxon   30      M           B.E                          7   
8      9    Oxon   31      F           B.E                          9   
9     10    Oxon   30      F           B.E                          8   
10    11   Bashh   24      M           M.E                          1   
11    12   Bashh   26      M           M.E                          3   
12    13   Bashh   34      F           M.E                         10   
13    14   Bashh   31      F           M.E                          7   
14    15   Bashh   35      F           M.E                         11   
15    16    palm   36      F           B.E                         13   
16    17    palm   38      F           B.E                         15   
17    18    palm   40      F           B.E                         18   
18    19    palm   41      F           B.E                         20   
19    20    palm   43      F           B.E                         21   
20    21     TSC   21      M           B.E                          0   
21    22     TSC   22      F           B.E                          0   
22    23     TSC   22      F           B.E                          1   
23    24     TSC   22      F           B.E                          0   
24    25     TSC   22      F           B.E                          1   

               Area of work  salary package per month  
0               programming                     30000  
1       predective analysis                     50000  
2   cloud server management                    120000  
3               programming                     42000  
4       predective analysis                     35000  
5   cloud server management                    100000  
6       predective analysis                    110000  
7               programming                     85000  
8       predective analysis                    200000  
9               programming                     95000  
10  cloud server management                     40000  
11  cloud server management                     65000  
12      predective analysis                    210000  
13      predective analysis                    160000  
14      predective analysis                    225000  
15              programming                    160000  
16              programming                    180000  
17      predective analysis                    320000  
18      predective analysis                    350000  
19  cloud server management                    500000  
20              programming                     25000  
21              programming                     26000  
22      predective analysis                     39000  
23      predective analysis                     30000  
24  cloud server management                     32000

In [29]:
df.drop(['S.No'],axis=1,inplace=True)
df

company  Age Gender Qualification  no of experience in years  \
0     ABBB   21      M           B.E                          0   
1     ABBB   24      F           M.E                          1   
2     ABBB   30      M           M.E                          5   
3     ABBB   23      M           B.E                          2   
4     ABBB   21      F           B.E                          0   
5     Oxon   27      M           B.E                          4   
6     Oxon   29      M           B.E                          5   
7     Oxon   30      M           B.E                          7   
8     Oxon   31      F           B.E                          9   
9     Oxon   30      F           B.E                          8   
10   Bashh   24      M           M.E                          1   
11   Bashh   26      M           M.E                          3   
12   Bashh   34      F           M.E                         10   
13   Bashh   31      F           M.E                          7   
14   Bashh   35      F           M.E                         11   
15    palm   36      F           B.E                         13   
16    palm   38      F           B.E                         15   
17    palm   40      F           B.E                         18   
18    palm   41      F           B.E                         20   
19    palm   43      F           B.E                         21   
20     TSC   21      M           B.E                          0   
21     TSC   22      F           B.E                          0   
22     TSC   22      F           B.E                          1   
23     TSC   22      F           B.E                          0   
24     TSC   22      F           B.E                          1   

               Area of work  salary package per month  
0               programming                     30000  
1       predective analysis                     50000  
2   cloud server management                    120000  
3               programming                     42000  
4       predective analysis                     35000  
5   cloud server management                    100000  
6       predective analysis                    110000  
7               programming                     85000  
8       predective analysis                    200000  
9               programming                     95000  
10  cloud server management                     40000  
11  cloud server management                     65000  
12      predective analysis                    210000  
13      predective analysis                    160000  
14      predective analysis                    225000  
15              programming                    160000  
16              programming                    180000  
17      predective analysis                    320000  
18      predective analysis                    350000  
19  cloud server management                    500000  
20              programming                     25000  
21              programming                     26000  
22      predective analysis                     39000  
23      predective analysis                     30000  
24  cloud server management                     32000

In [30]:
df = df.replace({'company': {'ABBB': 0,'Oxon': 1,'Bashh':2,'palm':3,'TSC':4}})
df = df.replace({'Gender': {'F': 0,'M': 1}})
df = df.replace({'Qualification': {'B.E': 0,'M.E': 1}})
df = df.replace({'Area of work': {'programming': 0,'predective analysis': 1,'cloud server management':2}})
df

company  Age  Gender  Qualification  no of experience in years  \
0         0   21       1              0                          0   
1         0   24       0              1                          1   
2         0   30       1              1                          5   
3         0   23       1              0                          2   
4         0   21       0              0                          0   
5         1   27       1              0                          4   
6         1   29       1              0                          5   
7         1   30       1              0                          7   
8         1   31       0              0                          9   
9         1   30       0              0                          8   
10        2   24       1              1                          1   
11        2   26       1              1                          3   
12        2   34       0              1                         10   
13        2   31       0              1                          7   
14        2   35       0              1                         11   
15        3   36       0              0                         13   
16        3   38       0              0                         15   
17        3   40       0              0                         18   
18        3   41       0              0                         20   
19        3   43       0              0                         21   
20        4   21       1              0                          0   
21        4   22       0              0                          0   
22        4   22       0              0                          1   
23        4   22       0              0                          0   
24        4   22       0              0                          1   

    Area of work  salary package per month  
0              0                     30000  
1              1                     50000  
2              2                    120000  
3              0                     42000  
4              1                     35000  
5              2                    100000  
6              1                    110000  
7              0                     85000  
8              1                    200000  
9              0                     95000  
10             2                     40000  
11             2                     65000  
12             1                    210000  
13             1                    160000  
14             1                    225000  
15             0                    160000  
16             0                    180000  
17             1                    320000  
18             1                    350000  
19             2                    500000  
20             0                     25000  
21             0                     26000  
22             1                     39000  
23             1                     30000  
24             2                     32000

In [31]:
X = df.iloc[:, 1:6].values
Y1 = df.iloc[:, 6].values
Y2 = df.iloc[:, 0].values
X_train, X_test, Y1_train, Y1_test = train_test_split(X,Y1,random_state=0, test_size=0.30)
X_train, X_test, Y2_train, Y2_test = train_test_split(X,Y2,random_state=0, test_size=0.30)

In [34]:
linear_regression=LinearRegression() #model for company
linear_regression.fit(df[['Age' ,'Gender','Qualification','no of experience in years','Area of work']],df.company)

LinearRegression()

In [56]:
linear_regression.predict([[31,1,0,9,1]]) #17th entry company prediction

array([1.5603021])

In [51]:
linear_regression1=LinearRegression() # model for salary
linear_regression1.fit(df[['company','Age' ,'Gender','Qualification','no of experience in years','Area of work']],df['salary package per month'])

LinearRegression()

In [53]:
linear_regression1.predict([[1,31,1,0,9,1]]) #salary prediction

array([175563.93319592])

In [57]:
linear_regression1.predict([[3,41,0,0,20,1]])

array([375314.23065835])